### PR TITLE
Fix issues where devices can get stuck

### PR DESCRIPTION
**Pull request by gunnarbeutner**
**Fix issue where devices get stuck at the upper end of the bounding box**

If the initial guess for the Nelder-Mead algorithm is close to the upper end of the bounding box Math.Net will sometimes fail to pick any test points that are inside the bounding box. It then falls back to using the initial guess as the solution, causing devices to get stuck at that location until the app is restarted. This seems to happen because the error value for those test points is all indentical (i.e. positive infinity).

This patch changes the error value calculation to add a gradient based on how far a test point is outside of the bounding box. This gives the optimization algorithm a sense of directionality. It also clamps the minimizing point to the bounding box in case we do end up with a solution that's outside of the bounding box.

This problem can be reproduced by setting at least two components of the the initial guess vector to the corresponding values of the upper bound of the bounding box:

For example, with `bounds: [[0, 0, 0], [15.26, 7.78, 2.5]]`:

```csharp
guess = new Point3D(15.26, 3.0, 2.5); // causes devices to get stuck
guess = new Point3D(15.25, 3.0, 2.5); // does not cause devices to get stuck
```

**Fix issue where devices can get stuck at X=0, Y=0 and Z=0**

This can happen because the initial test point picked by Math.Net is only 0.00025 units (for each vector component that is 0) away from the initial guess.

With this patch we're picking a (hopefully) better starting point by projecting a unit vector from the initial guess towards the centroid of the triangle that's described by the locations of the closest three nodes.

This problem can be reproduced by setting all vector components of the initial guess to 0:

```csharp
guess = new Point3D(0, 0, 0);
```

Most of the time some of the vector components of the solution will be zero temporarily - and at least some of the time the solution will converge on a value where at least one vector component is permanently zero until the app is restarted.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
The second patch also had a positive effect on location stability for me. Previously my devices would tend to oscillate between two points, like so:

https://github.com/ESPresense/ESPresense-companion/assets/388571/19c0ba3b-df0b-4d7d-afae-1ed844fedd33

WIth the patch this is happening a lot less.

**Comment by DTTerastar** [comment]
Excited to check this out.  I'm working on getting the distances a bit better on the esp32 right now

**Review by DTTerastar — APPROVED** [review]

**Comment by DTTerastar** [comment]
Does seem improved, approved!

**Comment by DTTerastar** [comment]
I'm noticing an issue.  It seems to push me from first floor to outside when i sit close to 0,0,0.

**Pull request merged**
