### PR TITLE
Aspect Ration 1:1

### PR DESCRIPTION
**Pull request by arne182**
Fixing https://github.com/ESPresense/ESPresense-companion/issues/126

### CODE REVIEW

**Review by DTTerastar — CHANGES_REQUESTED** [review]
I get a scroll bar:

image

**Comment by arne182** [comment]
Excellent. So that works then, is what you are saying?

**Comment by DTTerastar** [comment]
> Excellent. So that works then, is what you are saying?

Not exactly, it's very weird to have the scrollbar on top of the normal scale and move behavior.  Try this version see if it works better:  https://github.com/ESPresense/ESPresense-companion/pull/407

**Comment by arne182** [comment]
If only I knew how to load it into my home assistant. I am on a home assistant yellow. Can you tell me how I can load that code?

**Comment by DTTerastar** [comment]
You can't really develop on yellow, and i'm not aware of any good way of doing betas on HA Addons.  You can run it locally by installing the dotnetcore framework v7 and then run `dotnet watch`.

**Comment by arne182** [comment]
I am sure your approach is better than anything that me and  chat gpt could ever pull off. I am using this add on on my phone and the calibration page doesn't allow me to pan to the right
Screenshot_20231117_233923_Home Assistant
The experience is not great even if I move to landscape as I still can't see everything and can't move over
Screenshot_20231117_234045_Home Assistant

**Comment by DTTerastar** [comment]
Calibration is totally a different page with different issues.  I'm cool w/ any and all help.

**Pull request closed without merging**
